- name: Check Splunk apps
  hosts: splunkservers
  become: yes
  become_method: sudo
  become_user: splunk
  tasks:
  - name: Check apps
    check_splunk_apps: name={{ item }}
    with_items:
    - python_upgrade_readiness_app
    - splunk-dashboard-studio
    register: apps
  - name: Print apps
    debug:
        var: apps
