---
- name: Create splunk user on splunkservers
  hosts: splunkservers
  become: yes
  become_user: root
  tasks:
  - name: Create splunk user
    user:
      name: splunk
      uid: 2001
      shell: /opt/splunk/bin
  - name: check user
    command: ls -la /home
